### ISSUE TITLE
Why the ES module is not global in whole project

### ISSUE THREAD

**Issue by igortas** [ArkerLabs/event-sourcing-nestjs-example#1]
Hi,

How I can define the ES store in app.module.ts with the static method forRoot and use in feature folders, more like how typeorm is working.

BR, Igor

**Comment by Nytyr** [comment]
Hello,

TypeORM has two ways of importing it in your module, with _forRoot_ that creates the connection and provides you the classes, and the method _forFeature_, which just provides you the classes. 

Currently we just have the _forRoot_ method, which creates the connection and provides the classes, I will separate this in two methods.

**Comment by Nytyr** [comment]
Fixed.

Let me know if you have more problems.
