### ISSUE TITLE
How to combine the 2 examples?

### ISSUE THREAD

**Issue by RickyvdBerg** [ArkerLabs/event-sourcing-nestjs-example#2]
Im missing the usage of the events in this example. I would like to know how to rebuild objects from the events in this example. I tried it several ways but loadFromHistory is never resulting in an object that includes more than the Id. 

AggregateRoot
```typescript
export class Customer extends AggregateRoot {
    data!: CreateCustomerDto
    constructor(
      public readonly id: string,
      ) {
      super();
    }
}
```

Inside repo
```typescript
async findById(id: string): Promise<Customer> {
        const customer = new Customer(id)
        customer.loadFromHistory(await this.eventStore.getEvents('customer', id))
        return customer
    }
```

It correctly retreives the events belonging to the customer, but the object does not get transformed.

**Comment by Nytyr** [comment]
Hello!

Check this example: [HeroAggregate](https://github.com/Nytyr/nest-cqrs-eventsourcing-example/blob/master/src/heroes/models/hero.model.ts)

For every event you need a callback to reconstruct the aggregate state.

**Comment by Nytyr** [comment]
Closing. 
Feel free to reopen if you need more help or if you think we should add more documentation in the lib 👍
